disable

diff --git a/.github/workflows/clang_format.yml b/.github/workflows/clang_format.yml
--- a/.github/workflows/clang_format.yml
+++ b/.github/workflows/clang_format.yml
@@ -1,132 +1,132 @@
-name: SeqAn3 lint
+# name: SeqAn3 lint
 
-on:
-  pull_request_target:
+# on:
+#   pull_request_target:
 
-env:
-  TZ: Europe/Berlin
+# env:
+#   TZ: Europe/Berlin
 
-defaults:
-  run:
-    shell: bash -exo pipefail {0}
+# defaults:
+#   run:
+#     shell: bash -exo pipefail {0}
 
-jobs:
-  # Cancel other workflows that are dependent on this workflow by adding jobs that have the same concurrency group.
-  cancel_linux:
-    name: Cancel Linux
-    concurrency:
-      group: linux-${{ github.event.pull_request.number }}
-      cancel-in-progress: true
-    runs-on: ubuntu-22.04
-    steps:
-      - name: "Cancel Linux"
-        run: echo "Cancelling Linux"
-  cancel_macos:
-    name: Cancel macOS
-    concurrency:
-      group: macos-${{ github.event.pull_request.number }}
-      cancel-in-progress: true
-    runs-on: ubuntu-22.04
-    steps:
-      - name: "Cancel macOS"
-        run: echo "Cancelling macOS"
-  cancel_misc:
-    name: Cancel Misc
-    concurrency:
-      group: misc-${{ github.event.pull_request.number }}
-      cancel-in-progress: true
-    runs-on: ubuntu-22.04
-    steps:
-      - name: "Cancel Misc"
-        run: echo "Cancelling Misc"
-  lint:
-    name: clang-format
-    concurrency:
-      group: clang-format-${{ github.event.pull_request.number }}
-      cancel-in-progress: true
-    runs-on: ubuntu-22.04
-    timeout-minutes: 15
-    steps:
-      # - name: Add label
-      #   env:
-      #       GITHUB_TOKEN: ${{ secrets.SEQAN_ACTIONS_PAT }}
-      #       PR_URL: ${{ github.event.pull_request.html_url }}
-      #   run: gh pr edit $PR_URL --add-label "clang-format"
+# jobs:
+#   # Cancel other workflows that are dependent on this workflow by adding jobs that have the same concurrency group.
+#   cancel_linux:
+#     name: Cancel Linux
+#     concurrency:
+#       group: linux-${{ github.event.pull_request.number }}
+#       cancel-in-progress: true
+#     runs-on: ubuntu-22.04
+#     steps:
+#       - name: "Cancel Linux"
+#         run: echo "Cancelling Linux"
+#   cancel_macos:
+#     name: Cancel macOS
+#     concurrency:
+#       group: macos-${{ github.event.pull_request.number }}
+#       cancel-in-progress: true
+#     runs-on: ubuntu-22.04
+#     steps:
+#       - name: "Cancel macOS"
+#         run: echo "Cancelling macOS"
+#   cancel_misc:
+#     name: Cancel Misc
+#     concurrency:
+#       group: misc-${{ github.event.pull_request.number }}
+#       cancel-in-progress: true
+#     runs-on: ubuntu-22.04
+#     steps:
+#       - name: "Cancel Misc"
+#         run: echo "Cancelling Misc"
+#   lint:
+#     name: clang-format
+#     concurrency:
+#       group: clang-format-${{ github.event.pull_request.number }}
+#       cancel-in-progress: true
+#     runs-on: ubuntu-22.04
+#     timeout-minutes: 15
+#     steps:
+#       # - name: Add label
+#       #   env:
+#       #       GITHUB_TOKEN: ${{ secrets.SEQAN_ACTIONS_PAT }}
+#       #       PR_URL: ${{ github.event.pull_request.html_url }}
+#       #   run: gh pr edit $PR_URL --add-label "clang-format"
 
-      - name: Get fetch depth
-        id: fetch_depth
-        run: echo "::set-output name=depth::$(( ${{ github.event.pull_request.commits }} + 2 ))"
+#       - name: Get fetch depth
+#         id: fetch_depth
+#         run: echo "::set-output name=depth::$(( ${{ github.event.pull_request.commits }} + 2 ))"
 
-      - name: Checkout SeqAn3
-        uses: actions/checkout@v3
-        with:
-          repository: ${{ github.event.pull_request.head.repo.full_name }}
-          ref: ${{ github.event.pull_request.head.ref }}
-          path: seqan3
-          fetch-depth: ${{ steps.fetch_depth.outputs.depth }}
-          submodules: false
+#       - name: Checkout SeqAn3
+#         uses: actions/checkout@v3
+#         with:
+#           repository: ${{ github.event.pull_request.head.repo.full_name }}
+#           ref: ${{ github.event.pull_request.head.ref }}
+#           path: seqan3
+#           fetch-depth: ${{ steps.fetch_depth.outputs.depth }}
+#           submodules: false
 
-      - name: Get changed files
-        id: changed_files
-        uses: tj-actions/changed-files@v20
-        with:
-          path: seqan3
-          base_sha: ${{ github.event.pull_request.base.sha }}
-          sha: ${{ github.event.pull_request.head.sha }}
-          files: |
-            **/*.cpp
-            **/*.hpp
-            include/seqan3/std/*
-          files_ignore: |
-            include/seqan3/contrib/**
-            submodules/**
+#       - name: Get changed files
+#         id: changed_files
+#         uses: tj-actions/changed-files@v20
+#         with:
+#           path: seqan3
+#           base_sha: ${{ github.event.pull_request.base.sha }}
+#           sha: ${{ github.event.pull_request.head.sha }}
+#           files: |
+#             **/*.cpp
+#             **/*.hpp
+#             include/seqan3/std/*
+#           files_ignore: |
+#             include/seqan3/contrib/**
+#             submodules/**
 
-      - name: Show output
-        run: |
-          echo '${{ toJSON(steps.changed_files.outputs) }}'
+#       - name: Show output
+#         run: |
+#           echo '${{ toJSON(steps.changed_files.outputs) }}'
 
-      - name: Install clang-format
-        if: steps.changed_files.outputs.any_changed == 'true'
-        run: |
-          echo 'APT::Acquire::Retries "5";' | sudo tee -a /etc/apt/apt.conf.d/80-retries > /dev/null
-          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
-          sudo apt-add-repository --no-update --yes "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy main"
-          sudo apt-get update
-          sudo apt-get install --yes clang-format-15
+#       - name: Install clang-format
+#         if: steps.changed_files.outputs.any_changed == 'true'
+#         run: |
+#           echo 'APT::Acquire::Retries "5";' | sudo tee -a /etc/apt/apt.conf.d/80-retries > /dev/null
+#           wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
+#           sudo apt-add-repository --no-update --yes "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy main"
+#           sudo apt-get update
+#           sudo apt-get install --yes clang-format-15
 
-      - name: Run clang-format
-        if: steps.changed_files.outputs.any_changed == 'true'
-        run: |
-          cd seqan3
-          echo "${{ steps.changed_files.outputs.all_changed_files }}" | \
-          xargs clang-format-15 --style=file:.clang-format -i
+#       - name: Run clang-format
+#         if: steps.changed_files.outputs.any_changed == 'true'
+#         run: |
+#           cd seqan3
+#           echo "${{ steps.changed_files.outputs.all_changed_files }}" | \
+#           xargs clang-format-15 --style=file:.clang-format -i
 
-      # - name: Import GPG key
-      #   if: steps.changed_files.outputs.any_changed == 'true'
-      #   uses: crazy-max/ghaction-import-gpg@v4
-      #   with:
-      #     workdir: seqan3
-      #     gpg_private_key: ${{ secrets.SEQAN_ACTIONS_GPG_KEY }}
-      #     passphrase: ${{ secrets.SEQAN_ACTIONS_GPG_PASSPHRASE }}
-      #     git_user_signingkey: true
-      #     git_commit_gpgsign: true
+#       # - name: Import GPG key
+#       #   if: steps.changed_files.outputs.any_changed == 'true'
+#       #   uses: crazy-max/ghaction-import-gpg@v4
+#       #   with:
+#       #     workdir: seqan3
+#       #     gpg_private_key: ${{ secrets.SEQAN_ACTIONS_GPG_KEY }}
+#       #     passphrase: ${{ secrets.SEQAN_ACTIONS_GPG_PASSPHRASE }}
+#       #     git_user_signingkey: true
+#       #     git_commit_gpgsign: true
 
-      - name: Commit changes
-        if: steps.changed_files.outputs.any_changed == 'true'
-        uses: EndBug/add-and-commit@v9
-        with:
-          author_name: seqan-actions[bot]
-          author_email: seqan-actions@users.noreply.github.com
-          message: '[MISC] clang-format'
-          cwd: './seqan3'
+#       - name: Commit changes
+#         if: steps.changed_files.outputs.any_changed == 'true'
+#         uses: EndBug/add-and-commit@v9
+#         with:
+#           author_name: seqan-actions[bot]
+#           author_email: seqan-actions@users.noreply.github.com
+#           message: '[MISC] clang-format'
+#           cwd: './seqan3'
 
-      # # Wait for 5 seconds such that workflows triggered by adding the label run on the newest commit.
-      # - name: Defer workflow
-      #   if: steps.changed_files.outputs.any_changed == 'true'
-      #   run: sleep 5
+#       # # Wait for 5 seconds such that workflows triggered by adding the label run on the newest commit.
+#       # - name: Defer workflow
+#       #   if: steps.changed_files.outputs.any_changed == 'true'
+#       #   run: sleep 5
 
-      # - name: Remove label
-      #   env:
-      #       GITHUB_TOKEN: ${{ secrets.SEQAN_ACTIONS_PAT }}
-      #       PR_URL: ${{ github.event.pull_request.html_url }}
-      #   run: gh pr edit $PR_URL --remove-label "clang-format"
+#       # - name: Remove label
+#       #   env:
+#       #       GITHUB_TOKEN: ${{ secrets.SEQAN_ACTIONS_PAT }}
+#       #       PR_URL: ${{ github.event.pull_request.html_url }}
+#       #   run: gh pr edit $PR_URL --remove-label "clang-format"
